version: '3'

env:
  DOCKER_IMAGE_NAME: "alanut93/news_aggregator"
  DOCKER_IMAGE_TAG: "v1.0.18"
  DOCKERFILE_PATH: ".Dockerfile"
  DOCKER_PORT: "443"
  SERVER_EXPOSE_PORT: "443"
  HELM_CHART_NAME: "news-aggregator"

output:
  group:
    begin: '::group::{{.TASK}}'
    end: '::endgroup::'

tasks:
  tidy:
    desc: "Run go mod tidy"
    cmd: go mod tidy

  mocks-generate:
    desc: "Generate mocks for the project"
    cmd: go generate ./...

  test:
    desc: "Run all tests in the project."
    deps: [ mocks-generate ]
    cmd: go test ./...

  fmt:
    desc: "go fmt on all Go files"
    cmd: go fmt ./...

  vet:
    desc: "Run go vet on all Go files"
    cmd: go vet ./...

  docker-build:
    desc: "Run docker build"
    cmd: docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG -f $DOCKERFILE_PATH .

  docker-build-operator:
    desc: "Run docker build for operator image"
    cmd: docker build -t alanut93/updater:v1.0.2 -f operator/Dockerfile .

  docker-run:
    desc: "Run docker container"
    cmd: docker run -d -p $DOCKER_PORT:$SERVER_EXPOSE_PORT $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG

  cli-run:
    desc: "Run the CLI locally"
    cmd: go run cmd/command-line-client/main.go

  server-run:
    desc: "Run the web server locally"
    cmd: go run cmd/web/main.go

  check-all:
    desc: "Run all checks: mod tidy, fmt, tests and vet"
    cmds:
      - task: tidy
      - task: fmt
      - task: test
      - task: vet

  create-namespace:
    desc: "Create a Kubernetes namespace if it does not exist"
    cmds:
        - |
          if ! kubectl get namespace news-aggregator >/dev/null 2>&1; then
            kubectl create namespace news-aggregator
            echo "Namespace news-aggregator created"
          else
            echo "Namespace news-aggregator already exists"
          fi

  delete-namespace:
    cmd: kubectl delete namespace news-aggregator
    desc: "Delete a Kubernetes namespace"

  deploy:
    desc: "Deploys news-aggregator app on Kubernetes cluster"
    deps: [ create-namespace ]
    cmds:
      - kubectl apply -f templates

  undeploy:
    desc: "Removes news-aggregator app from Kubernetes cluster"
    cmds:
      - kubectl delete -f templates

  createChart:
    desc: "Creates a Helm chart for news-aggregator"
    cmds:
      - helm package ./helm-chart
      - mkdir -p ./helm-chart
      - mv *.tgz ./helm-chart/
    silent: true

  installChart:
    desc: "Installs the Helm chart on the Kubernetes cluster"
    deps: [ create-namespace ]
    cmds:
      - helm install $HELM_CHART_NAME ./$HELM_CHART_NAME --namespace news-aggregator

  uninstallChart:
    desc: "Uninstalls the Helm chart from the Kubernetes cluster"
    cmds:
      - helm uninstall $HELM_CHART_NAME --namespace news-aggregator
