version: '3'

env:
  DOCKER_IMAGE_NAME: "alanut93/news_aggregator"
  DOCKER_IMAGE_TAG: "v1.0.18"
  DOCKERFILE_PATH: ".Dockerfile"
  DOCKER_PORT: "443"
  SERVER_EXPOSE_PORT: "443"

output:
  group:
    begin: '::group::{{.TASK}}'
    end: '::endgroup::'

tasks:
  tidy:
    desc: "Run go mod tidy"
    cmd: go mod tidy

  mocks-generate:
    desc: "Generate mocks for the project"
    cmd: go generate ./...

  test:
    desc: "Run all tests in the project."
#    deps: [ mocks-generate ]
    cmd: go test  ./storage/news/... ./storage/source/... ./web/feed/...

  fmt:
    desc: "go fmt on all Go files"
    cmd: go fmt ./...

  vet:
    desc: "Run go vet on all Go files"
    cmd: go vet ./...

  docker-build:
    desc: "Run docker build"
    cmd: docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG -f $DOCKERFILE_PATH .

  docker-run:
    desc: "Run docker container"
    cmd: docker run -d -p $DOCKER_PORT:$SERVER_EXPOSE_PORT $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG

  cli-run:
    desc: "Run the CLI locally"
    cmd: go run cmd/command-line-client/main.go

  server-run:
    desc: "Run the web server locally"
    cmd: go run cmd/web/main.go

  check-all:
    desc: "Run all checks: mod tidy, fmt, vet, and tests"
    cmds:
#      - task: tidy
#      - task: fmt
      - task: test
#      - task: vet

  create-namespace:
    desc: "Create a Kubernetes namespace if it does not exist"
    cmds:
      - |
        if ! kubectl get namespace {{.namespace_name}} >/dev/null 2>&1; then
          kubectl create namespace {{.namespace_name}}
          echo "Namespace {{.namespace_name}} created"
        else
          echo "Namespace {{.namespace_name}} already exists"
        fi

  delete-namespace:
    cmd: kubectl delete namespace {{.namespace_name}}
    desc: "Delete a Kubernetes namespace"

  deploy:
    desc: "Deploys news-aggregator app on Kubernetes cluster"
    deps: [ create-namespace ]
    cmds:
      - kubectl apply -f {{.k8s_folder}}

  undeploy:
    desc: "Removes news-aggregator app from Kubernetes cluster"
    cmds:
      - kubectl delete -f {{.k8s_folder}}
