apiVersion: v2
name: ivan-news-aggregator-chart
version: 0.1.0
type: application
appVersion: "1.0.19"
dependencies:
  - name: vertical-pod-autoscaler
    version: "1.7.0"
    repository: "https://stevehipwell.github.io/helm-charts/"
