replicaCount: 1
name: "news-aggregator"
containerPort: 443
imageName: "406477933661.dkr.ecr.eu-west-2.amazonaws.com/ivan-news-aggregator-server:v1.0.18"
updaterImageName: "406477933661.dkr.ecr.eu-west-2.amazonaws.com/ivan-news-aggregator-updater:v1.0.2"
namespace: "news-aggregator"
serviceAccount: "news-aggregator-service-account"
serviceName: "news-aggregator-service"
accessKey: ""
privateAccessKey: ""

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

vpa:
  minAllowed:
    cpu: "300m"
    memory: "50Mi"
  maxAllowed:
    cpu: "500m"
    memory: "500Mi"

service:
  port: 443
  targetPort: 443
