apiVersion: batch/v1
kind: CronJob
metadata:
  name: aws-cronjob
  namespace: {{ .Values.namespace }}
spec:
  schedule: "0 9 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: news-aggregator-service-account
          containers:
            - name: aws-cronjob
              image: alpine:3.18
              env:
                - name: ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: aws-secret
                      key: accessKey
                - name: PRIVATE_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: aws-secret
                      key: privateAccessKey
              command:
                - echo $ACCESS_KEY
                - /bin/sh
                  - -c
                  - |
                  wget https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -O awscliv2.zip
                  unzip awscliv2.zip
                  ./aws/install
                  
                  wget https://get.helm.sh/helm-v3.9.0-linux-amd64.tar.gz -O helm.tar.gz
                  tar -zxvf helm.tar.gz --strip-components=1 -C /usr/local/bin linux-amd64/helm
                  
                  curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
                  chmod +x kubectl
                  mv kubectl /usr/local/bin/

                - aws configure set aws_access_key_id $ACCESS_KEY
                - aws configure set aws_secret_access_key $PRIVATE_ACCESS_KEY
                - aws configure set region eu-west-1
                - aws configure set output json
                - aws ecr get-login-password --region eu-west-1 | helm registry login --username AWS --password-stdin 406477933661.dkr.ecr.eu-west-1.amazonaws.com
                - aws ecr get-login-password --region eu-west-1 | kubectl create secret docker-registry ecr-registry-secret --docker-server=406477933661.dkr.ecr.eu-west-1.amazonaws.com --docker-username=AWS --docker-password=$(aws ecr get-login-password --region eu-west-1) --namespace news-aggregator
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1