apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: news-aggregator-pvc-mnt
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.5Gi