apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  accessKey: {{ .Values.accessKey }}
  privateAccessKey: {{ .Values.privateAccessKey }}