apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-aggregator-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: news-aggregator
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: news-aggregator
  template:
    metadata:
      labels:
        app: news-aggregator
    spec:
      serviceAccountName: {{ .Values.serviceAccount }}
      containers:
        - name: news-aggregator
          image: {{ .Values.imageName }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          volumeMounts:
            - mountPath: "/mnt"
              name: news-aggregator-mnt
      volumes:
        - name: news-aggregator-mnt
          persistentVolumeClaim:
            claimName: news-aggregator-pvc-mnt
