apiVersion: v1
kind: Service
metadata:
  name: news-aggregator-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: news-aggregator
  ports:
    - name: service-ports
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
