apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: news-aggregator-apps
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: news-aggregator
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/ivan-poltavskiy/news-aggregator
    path: argocd/apps
    targetRevision: master
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
