apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-aggregator-deployment
  namespace: news-aggregator
  labels:
    app: news-aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news-aggregator
  template:
    metadata:
      labels:
        app: news-aggregator
    spec:
      serviceAccountName: news-aggregator-service-account
      containers:
        - name: news-aggregator
          image: alanut93/news_aggregator:v1.0.18
          ports:
            - containerPort: 443
          volumeMounts:
            - mountPath: "/mnt"
              name: news-aggregator-mnt
      volumes:
        - name: news-aggregator-mnt
          persistentVolumeClaim:
            claimName: news-aggregator-pvc-mnt
