apiVersion: v1
kind: PersistentVolume
metadata:
  name: news-aggregator-pv-storage
  namespace: news-aggregator
spec:
  capacity:
    storage: 0.5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/news-aggregator/storage"
