apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: news-aggregator-pvc-storage
  namespace: news-aggregator
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.5Gi