apiVersion: v1
kind: Service
metadata:
  name: news-aggregator-service
  namespace: news-aggregator
spec:
  selector:
    app: news-aggregator
  ports:
    - name: service-ports
      protocol: TCP
      port: 443
      targetPort: 443