apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: news-aggregator-role
  namespace: news-aggregator
rules:


---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: news-aggregator-rolebinding
  namespace: news-aggregator
subjects:
  - kind: ServiceAccount
    name: news-aggregator-service-account
    namespace: news-aggregator
roleRef:
  kind: Role
  name: news-aggregator-role
  apiGroup: rbac.authorization.k8s.io
