version: '3'

output:
  group:
    begin: '::group::{{.TASK}}'
    end: '::endgroup::'

tasks:
  tidy:
    desc: "Run go mod tidy"
    cmd: go mod tidy

  mocks-generate:
    desc: "Generate mocks for the project"
    cmd: go generate ./...

  test:
    desc: "Run all tests in the project."
    deps: [ mocks-generate ]
    cmd: go test ./...

  fmt:
    desc: "go fmt on all Go files"
    cmd: go fmt ./...

  vet:
    desc: "Run go vet on all Go files"
    cmd: go vet ./...

  cli-run:
    desc: "Run the CLI locally"
    cmd: go run main.go

  check-all:
    desc: "Run all checks: mod tidy, fmt, tests and vet"
    cmds:
      - task: tidy
      - task: fmt
      - task: test
      - task: vet