---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-service-account
  namespace: {{ .Values.news_aggregator.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.news_aggregator.namespace }}
  name: role-full-access-to-secrets
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["regcred"]
    verbs: ["delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-binding
  namespace: {{ .Values.news_aggregator.namespace }}
subjects:
  - kind: ServiceAccount
    name: aws-service-account
    namespace: {{ .Values.news_aggregator.namespace }}
    apiGroup: ""
roleRef:
  kind: Role
  name: role-full-access-to-secrets
  apiGroup: ""
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-service-account
  namespace: {{ .Values.operator_system.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.operator_system.namespace }}
  name: role-full-access-to-secrets
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["regcred"]
    verbs: ["delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-binding
  namespace: {{ .Values.operator_system.namespace }}
subjects:
  - kind: ServiceAccount
    name: aws-service-account
    namespace: {{ .Values.operator_system.namespace }}
    apiGroup: ""
roleRef:
  kind: Role
  name: role-full-access-to-secrets
  apiGroup: ""