---
apiVersion: v1
kind: Secret
metadata:
  name: ecr-registry-helper-secrets
  namespace: {{ .Values.namespace }}
stringData:
  AWS_SECRET_ACCESS_KEY: "{{.Values.privateAccessKey}}"
  AWS_ACCESS_KEY_ID: "{{.Values.accessKey}}"
  AWS_ACCOUNT: "{{ .Values.aws_account_id }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ecr-registry-helper-cm
  namespace: {{ .Values.namespace }}
data:
  AWS_REGION: "{{ .Values.aws_region }}"
  DOCKER_SECRET_NAME: "{{ .Values.docker_secret_name}}"
