version: '3'

vars:
  IMG: "alanut93/news-aggregator-operator:v1.0.3"
  ENVTEST_K8S_VERSION: "1.30.0"
  CONTAINER_TOOL: "docker"
  KUBECTL: "kubectl"
  KUSTOMIZE_VERSION: "v5.4.2"
  CONTROLLER_TOOLS_VERSION: "v0.15.0"
  ENVTEST_VERSION: "release-0.18"
  GOLANGCI_LINT_VERSION: "v1.59.1"
  PLATFORMS: "linux/arm64,linux/amd64,linux/s390x,linux/ppc64le"
  ignore_not_found: "false"

tasks:
  default:
    cmds:
      - task: build

  help:
    desc: "Display help"
    cmds:
      - |
        echo "Usage:"
        echo "  task [target]"
        echo ""
        echo "Targets:"
        task: list

  list:
    desc: "List available tasks"
    cmds:
      - task: help

  manifests:
    desc: "Generate WebhookConfiguration, ClusterRole and CustomResourceDefinition objects."
    cmds:
      - |
        LOCALBIN=$(pwd)/bin
        CONTROLLER_GEN=$LOCALBIN/controller-gen
        $CONTROLLER_GEN rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases

  generate:
    desc: "Generate code containing DeepCopy, DeepCopyInto, and DeepCopyObject method implementations."
    cmds:
      - |
        LOCALBIN=$(pwd)/bin
        CONTROLLER_GEN=$LOCALBIN/controller-gen
        $CONTROLLER_GEN object:headerFile="hack/boilerplate.go.txt" paths="./..."

  fmt:
    desc: "Run go fmt against code."
    cmds:
      - "go fmt ./..."

  vet:
    desc: "Run go vet against code."
    cmds:
      - "go vet ./..."

  test:
    desc: "Run tests."
    cmds:
      - |
        LOCALBIN=$(pwd)/bin
        ENVTEST=$LOCALBIN/setup-envtest
        KUBEBUILDER_ASSETS="$($ENVTEST use {{.ENVTEST_K8S_VERSION}} --bin-dir $LOCALBIN -p path)" \
        go test $(go list ./... | grep -v /e2e) -coverprofile cover.out

  test-e2e:
    desc: "Run the e2e tests against a Kind k8s instance that is spun up."
    cmds:
      - "go test ./test/e2e/ -v -ginkgo.v"

  lint:
    desc: "Run golangci-lint linter"
    cmds:
      - |
        LOCALBIN=$(pwd)/bin
        GOLANGCI_LINT=$LOCALBIN/golangci-lint
        $GOLANGCI_LINT run

  lint-fix:
    desc: "Run golangci-lint linter and perform fixes"
    cmds:
      - |
        LOCALBIN=$(pwd)/bin
        GOLANGCI_LINT=$LOCALBIN/golangci-lint
        $GOLANGCI_LINT run --fix

  build:
    desc: "Build manager binary."
    cmds:
      - task: manifests
      - task: generate
      - task: fmt
      - task: vet
      - "go build -o bin/manager cmd/main.go"

  run:
    desc: "Run a controller from your host."
    cmds:
      - task: manifests
      - task: generate
      - task: fmt
      - task: vet
      - "go run ./cmd/main.go"

  docker-build:
    desc: "Build docker image with the manager."
    cmds:
      - "{{.CONTAINER_TOOL}} build -t {{.IMG}} ."

  docker-push:
    desc: "Push docker image with the manager."
    cmds:
      - "{{.CONTAINER_TOOL}} push {{.IMG}}"

  docker-buildx:
    desc: "Build and push docker image for the manager for cross-platform support."
    cmds:
      - |
        sed -e '1 s/^FROM/FROM --platform=$${BUILDPLATFORM}/; t' -e '1,// s//FROM --platform=$${BUILDPLATFORM}/' Dockerfile > Dockerfile.cross
        {{.CONTAINER_TOOL}} buildx create --name operator-builder
        {{.CONTAINER_TOOL}} buildx use operator-builder
        {{.CONTAINER_TOOL}} buildx build --push --platform={{.PLATFORMS}} --tag {{.IMG}} -f Dockerfile.cross .
        {{.CONTAINER_TOOL}} buildx rm operator-builder
        rm Dockerfile.cross

  build-installer:
    desc: "Generate a consolidated YAML with CRDs and deployment."
    cmds:
      - task: manifests
      - task: generate
      - task: kustomize
      - |
        mkdir -p dist
        cd config/manager && {{.KUSTOMIZE}} edit set image controller={{.IMG}}
        {{.KUSTOMIZE}} build config/default > dist/install.yaml

  install:
    desc: "Install CRDs into the K8s cluster specified in ~/.kube/config."
    cmds:
      - task: manifests
      - task: kustomize
      - "{{.KUSTOMIZE}} build config/crd | {{.KUBECTL}} apply -f -"

  uninstall:
    desc: "Uninstall CRDs from the K8s cluster specified in ~/.kube/config."
    cmds:
      - task: manifests
      - task: kustomize
      - "{{.KUSTOMIZE}} build config/crd | {{.KUBECTL}} delete --ignore-not-found={{.ignore_not_found}} -f -"

  deploy:
    desc: "Deploy controller to the K8s cluster specified in ~/.kube/config."
    cmds:
      - task: manifests
      - task: kustomize
      - |
        LOCALBIN=$(pwd)/bin
        KUSTOMIZE=$LOCALBIN/kustomize
        cd config/manager && $KUSTOMIZE edit set image controller={{.IMG}}
        cd - # Return to previous directory
        $KUSTOMIZE build config/default | {{.KUBECTL}} apply -f -

  undeploy:
    desc: "Undeploy controller from the K8s cluster specified in ~/.kube/config."
    cmds:
      - |
        LOCALBIN=$(pwd)/bin
        KUSTOMIZE=$LOCALBIN/kustomize
        $KUSTOMIZE build config/default | {{.KUBECTL}} delete --ignore-not-found={{.ignore_not_found}} -f -

  kustomize:
    desc: "Download kustomize locally if necessary."
    cmds:
      - |
        LOCALBIN=$(pwd)/bin
        if [ ! -f "$LOCALBIN/kustomize-{{.KUSTOMIZE_VERSION}}" ]; then \
          echo "Downloading kustomize"; \
          rm -f "$LOCALBIN/kustomize" || true; \
          GOBIN=$LOCALBIN go install sigs.k8s.io/kustomize/kustomize/v5@{{.KUSTOMIZE_VERSION}} ;\
          mv $LOCALBIN/kustomize $LOCALBIN/kustomize-{{.KUSTOMIZE_VERSION}}; \
        fi
        ln -sf $LOCALBIN/kustomize-{{.KUSTOMIZE_VERSION}} $LOCALBIN/kustomize

  controller-gen:
    desc: "Download controller-gen locally if necessary."
    cmds:
      - |
        LOCALBIN=$(pwd)/bin
        if [ ! -f "$LOCALBIN/controller-gen-{{.CONTROLLER_TOOLS_VERSION}}" ]; then \
          echo "Downloading controller-gen"; \
          rm -f "$LOCALBIN/controller-gen" || true; \
          GOBIN=$LOCALBIN go install sigs.k8s.io/controller-tools/cmd/controller-gen@{{.CONTROLLER_TOOLS_VERSION}} ;\
          mv $LOCALBIN/controller-gen $LOCALBIN/controller-gen-{{.CONTROLLER_TOOLS_VERSION}}; \
        fi
        ln -sf $LOCALBIN/controller-gen-{{.CONTROLLER_TOOLS_VERSION}} $LOCALBIN/controller-gen

  envtest:
    desc: "Download setup-envtest locally if necessary."
    cmds:
      - |
        LOCALBIN=$(pwd)/bin
        if [ ! -f "$LOCALBIN/setup-envtest-{{.ENVTEST_VERSION}}"]; then \
          echo "Downloading setup-envtest"; \
          rm -f "$LOCALBIN/setup-envtest" || true; \
          GOBIN=$LOCALBIN go install sigs.k8s.io/controller-runtime/tools/setup-envtest@{{.ENVTEST_VERSION}} ;\
          mv $LOCALBIN/setup-envtest $LOCALBIN/setup-envtest-{{.ENVTEST_VERSION}}; \
        fi
        ln -sf $LOCALBIN/setup-envtest-{{.ENVTEST_VERSION}} $LOCALBIN/setup-envtest

  golangci-lint:
    desc: "Download golangci-lint locally if necessary."
    cmds:
      - |
        LOCALBIN=$(pwd)/bin
        if [ ! -f "$LOCALBIN/golangci-lint-{{.GOLANGCI_LINT_VERSION}}"]; then \
          echo "Downloading golangci-lint"; \
          rm -f "$LOCALBIN/golangci-lint" || true; \
          GOBIN=$LOCALBIN go install github.com/golangci/golangci-lint/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}} ;\
          mv $LOCALBIN/golangci-lint $LOCALBIN/golangci-lint-{{.GOLANGCI_LINT_VERSION}}; \
        fi
        ln -sf $LOCALBIN/golangci-lint-{{.GOLANGCI_LINT_VERSION}} $LOCALBIN/golangci-lint
