name: Go

on:
  push:
    branches: [ "**" ]
  pull_request:
    types: [ opened, ready_for_review ]
    branches: [ "**" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.3'

      - name: Install Taskfile
        run: |
          sh -c "$(curl -sL https://taskfile.dev/install.sh)"
          sudo mv ./bin/task /usr/local/bin/task

      - name: Configure AWS
        run: |
          aws configure set aws_access_key_id ${{ secrets.ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.PRIVATE_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_REGION }}

      - name: Login to AWS
        run: task aws-auth-helm

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check for formatting changes
        run: |
          git diff --exit-code > /dev/null
          if [ $? -ne 0 ]; then
            echo "Formatting changes detected. Please run 'task fmt' locally and commit the changes."
            exit 1
          else
            echo "No formatting changes detected."
          fi
      - name: Push Helm chart
        run: |
          task pushChart
          task aws-image-push-server
          task aws-image-push-updater
          cd operator
          task docker_login
          task docker-build
          task docker-push
          cd ..

#      - name: Push news aggregator server to AWS ECR
#        run: task aws-image-push-server
#
#      - name: Push news aggregator updater to AWS ECR
#        run: task aws-image-push-updater
#
#      - name: Push operator to AWS ECR
#        run: |
#
#          cd operator
#          task docker-build
#          task docker-push
#          cd ..