name: release-please

on:
  push:
    branches:
      - feature/add-realese-please
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      major: ${{ steps.release.outputs.major }}
      minor: ${{ steps.release.outputs.minor }}
      patch: ${{ steps.release.outputs.patch }}
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: actions/checkout@v4

      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          config-file: release-please-config.json
          manifest-file: release-please-manifest.json

  build-and-push-docker:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build and push Docker image
        env:
          MAJOR_VERSION: ${{ needs.release-please.outputs.major }}
          MINOR_VERSION: ${{ needs.release-please.outputs.minor }}
          PATCH_VERSION: ${{ needs.release-please.outputs.patch }}
        run: |
          IMAGE_TAG="v${MAJOR_VERSION}.${MINOR_VERSION}.${PATCH_VERSION}"
          echo "Building Docker image with tag: ${IMAGE_TAG}"
          docker build -t ${{ secrets.DOCKER_USERNAME }}/news_aggregator:${IMAGE_TAG} -f .Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/news_aggregator:${IMAGE_TAG}