name: release-please

on:
  push:
    branches:
      - add-release-please

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run release-please
        uses: googleapis/release-please-action@v4
        with:
          release-type: go
          tag-separator: "@"
          include-component-in-tag: true
          token: ${{ secrets.GITHUB_TOKEN }}
