name: release-please

on:
  push:
    branches:
      - master
      - feature/add-realese-please
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run release-please
        id: create-version
        uses: googleapis/release-please-action@v4
        with:
          release-type: go
          token: ${{ secrets.GITHUB_TOKEN }}
          target-branch: ${{ github.ref_name }}

      - name: Debug release-please output
        run: |
            echo "Release-please outputs:"
            echo "Version: ${{ steps.create-version.outputs.version }}"
            echo "Major: ${{ steps.create-version.outputs.major }}"
            echo "Minor: ${{ steps.create-version.outputs.minor }}"
            echo "Patch: ${{ steps.create-version.outputs.patch }}"

      - name: Extract version from release-please output
        id: extract-version
        run: |
          VERSION=$(echo "${{ steps.create-version.outputs.version }}" | sed 's/^v//')
          echo "Extracted VERSION: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Debug extracted version
        run: |
          echo "Extracted version from GITHUB_ENV: ${{ steps.create-version.outputs.version }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        if: ${{ steps.release.outputs.release_created }}
        run: |
          IMAGE_TAG=${{ env.VERSION }}
          echo "Building Docker image with tag: ${IMAGE_TAG}"
          docker build -t ${{ secrets.DOCKER_USERNAME }}/news_aggregator:${IMAGE_TAG} -f .Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/news_aggregator:${IMAGE_TAG}