name: release-please

on:
  push:
    branches:
      - add-release-please

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run release-please
        id: create-version
        uses: googleapis/release-please-action@v4
        with:
          release-type: go
          tag-separator: "@"
          include-component-in-tag: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        env:
          MAJOR_VERSION: ${{ create-version.outputs.major }}
          MINOR_VERSION: ${{ create-version.outputs.minor }}
          PATCH_VERSION: ${{ create-version.outputs.patch }}
        run: |
          IMAGE_TAG="v${MAJOR_VERSION}.${MINOR_VERSION}.${PATCH_VERSION}"
          echo "Building Docker image with tag: ${IMAGE_TAG}"
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ivan/news_aggregator:${IMAGE_TAG} .
          docker push ${{ secrets.DOCKER_USERNAME }}/news-aggregator:${IMAGE_TAG}